const PDFDocument = require('pdfkit');
const receiptRepository = require('../repositories/receiptRepository');
const ApiError = require('../utils/ApiError');
const { formatCurrency } = require('../utils/helpers');

class ReceiptService {
  async getAll(filters) { return receiptRepository.findAll(filters); }

  async getById(id) {
    const r = await receiptRepository.findById(id);
    if (!r) throw new ApiError(404, 'Receipt not found');
    return r;
  }

  /**
   * Generate PDF receipt and stream to response
   * Uses PDFKit for professional receipt layout
   */
  async generatePDF(id, res) {
    const receipt = await receiptRepository.findById(id);
    if (!receipt) throw new ApiError(404, 'Receipt not found');

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=receipt-${receipt.receipt_no}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('STUDENT FEE MANAGEMENT SYSTEM', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Official Payment Receipt', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown();

    // Receipt Info
    doc.fontSize(11).font('Helvetica-Bold');
    doc.text(`Receipt No: ${receipt.receipt_no}`, 50);
    doc.text(`Date: ${new Date(receipt.generated_at).toLocaleDateString('en-IN')}`, 350, doc.y - 15);
    doc.moveDown();

    // Student Info
    doc.font('Helvetica-Bold').text('Student Details', 50);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10);
    doc.text(`Name: ${receipt.student_name}`);
    doc.text(`Student ID: ${receipt.student_code}`);
    doc.text(`Department: ${receipt.department}`);
    doc.text(`Email: ${receipt.student_email}`);
    doc.text(`Academic Year: ${receipt.academic_year}`);
    doc.moveDown();

    // Payment Details
    doc.font('Helvetica-Bold').fontSize(11).text('Payment Details', 50);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10);
    doc.text(`Fee Category: ${receipt.fee_category}`);
    doc.text(`Structure Amount: ${formatCurrency(receipt.structure_amount)}`);
    doc.text(`Amount Paid: ${formatCurrency(receipt.amount_paid)}`);
    doc.text(`Payment Method: ${receipt.payment_method}`);
    doc.text(`Transaction Ref: ${receipt.transaction_ref || 'N/A'}`);
    doc.text(`Payment Date: ${new Date(receipt.payment_date).toLocaleString('en-IN')}`);
    doc.text(`Status: ${receipt.payment_status}`);
    doc.moveDown();

    // Footer
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown();
    doc.fontSize(9).text(`Generated by: ${receipt.generated_by || 'System'}`, 50);
    doc.text('This is a computer-generated receipt and does not require a signature.', { align: 'center' });

    doc.end();
  }
}

module.exports = new ReceiptService();
